version: '3'
services:
  backend:
    image: kuunika/aefii-self-reporting-middle-layer-api:latest
    restart: always
    ports:
      - '3000:3000'
    volumes:
     - ./logs:/usr/src/app/logs
    env_file:
      - .env
    container_name: aefi
    
